export const tenExample1 = [
    "湯が<span style='color: #2e2e2e;'>沸いた</span> <span style='color: #bfbfbf;'>Yu ga waita - The water boiled</span><br>",
    "<span style='color: #2e2e2e;'>沸騰する</span>前に止めて <span style='color: #bfbfbf;'>Futtou suru mae ni tomete - Stop before it boils</span><br>",
    "やかんで水を<span style='color: #2e2e2e;'>沸かす</span> <span style='color: #bfbfbf;'>Yakan de mizu o wakasu - Boiling water in a kettle</span><br>",
    "<span style='color: #2e2e2e;'>沸騰している</span>湯気がすごい <span style='color: #bfbfbf;'>Futtou shiteiru yuge ga sugoi - The steam from boiling is intense</span><br>",
    "<span style='color: #2e2e2e;'>沸騰する</span>と音がする <span style='color: #bfbfbf;'>Futtou suru to oto ga suru - There's a sound when it boils</span><br>",
    "<span style='color: #2e2e2e;'>沸騰したら</span>すぐ火を止めて <span style='color: #bfbfbf;'>Futtou shitara sugu hi o tomete - Turn off the heat as soon as it boils</span><br>",
    "<span style='color: #2e2e2e;'>沸騰する</span>まで待って <span style='color: #bfbfbf;'>Futtou suru made matte - Wait until it boils</span><br>",
    "<span style='color: #2e2e2e;'>沸騰した</span>熱いお湯がほしい <span style='color: #bfbfbf;'>Futtou shita atsui oyu ga hoshii - I want boiling hot water</span><br>",
    "<span style='color: #2e2e2e;'>沸騰する</span>前に取り出して <span style='color: #bfbfbf;'>Futtou suru mae ni toridashite - Take it out before it boils</span><br>",
    "湯を<span style='color: #2e2e2e;'>沸かす</span>ときに火を強くする <span style='color: #bfbfbf;'>Yu o wakasu toki ni hi o tsuyoku suru - Increase the heat when boiling water</span><br>",
    "鍋で湯を<span style='color: #2e2e2e;'>沸かしています</span> <span style='color: #bfbfbf;'>Nabe de yu o wakashiteimasu - Boiling water in the pot</span><br>",];
export const tenExample2 = [
    "<span style='color: #2e2e2e;'>需要</span>が高いです <span style='color: #bfbfbf;'>Juyou ga takai desu - The demand is high</span><br>",
    "その商品は<span style='color: #2e2e2e;'>需要</span>があります <span style='color: #bfbfbf;'>Sono shouhin wa juyou ga arimasu - There is demand for that product</span><br>",
    "<span style='color: #2e2e2e;'>需要</span>を満たす必要があります <span style='color: #bfbfbf;'>Juyou o mitasu hitsuyou ga arimasu - There is a need to meet the demand</span><br>",
    "<span style='color: #2e2e2e;'>需要</span>が急速に増えています <span style='color: #bfbfbf;'>Juyou ga kyuusoku ni fueteimasu - The demand is increasing rapidly</span><br>",
    "<span style='color: #2e2e2e;'>需要予測</span>が難しいです <span style='color: #bfbfbf;'>Juyou yosoku ga muzukashii desu - Forecasting demand is difficult</span><br>",
    "そのサービスには<span style='color: #2e2e2e;'>需要</span>がありますか？ <span style='color: #bfbfbf;'>Sono saabisu ni wa juyou ga arimasu ka? - Is there a demand for that service?</span><br>",
    "<span style='color: #2e2e2e;'>需要</span>に応じて製品を調整します <span style='color: #bfbfbf;'>Juyou ni oujite seihin o chousei shimasu - We adjust the products according to the demand</span><br>",
    "<span style='color: #2e2e2e;'>需要</span>を満たすために努力しています <span style='color: #bfbfbf;'>Juyou o mitasu tame ni doryoku shiteimasu. - We are making efforts to meet the demand</span><br>",
    "<span style='color: #2e2e2e;'>需要</span>が予想以上でした <span style='color: #bfbfbf;'>Juyou ga yosou ijou deshita. - The demand exceeded expectations</span><br>",
    "<span style='color: #2e2e2e;'>需要</span>が安定しています <span style='color: #bfbfbf;'>Juyou ga antei shiteimasu. - The demand is stable</span><br>",];
export const tenExample3 = [
    "虫刺されで<span style='color: #2e2e2e;'>腫れた</span> <span style='color: #bfbfbf;'>Mushi sasare de hareta - I got swollen from a bug bite</span><br>",
    "目が<span style='color: #2e2e2e;'>腫れています</span> <span style='color: #bfbfbf;'>Me ga harete imasu - My eyes are swollen</span><br>",
    "喉が<span style='color: #2e2e2e;'>腫れている</span>ようだ <span style='color: #bfbfbf;'>Nodo ga harete iru you da - Looks like my throat is swollen</span><br>",
    "けがで足が<span style='color: #2e2e2e;'>腫れました</span> <span style='color: #bfbfbf;'>Kega de ashi ga hare mashita - My leg got swollen from the injury</span><br>",
    "その蚊に刺されて<span style='color: #2e2e2e;'>腫れた</span> <span style='color: #bfbfbf;'>Sono ka ni sasarete hareta - I got swollen from that mosquito bite</span><br>",
    "手が<span style='color: #2e2e2e;'>腫れてて</span>動かせない <span style='color: #bfbfbf;'>Te ga harete te ugokasenai - My hand is swollen, and I can't move it</span><br>",
    "彼の体に<span style='color: #2e2e2e;'>腫瘍</span>が見つかった <span style='color: #bfbfbf;'>Kare no karada ni shuyou ga mitsukatta - A tumor was found in his body</span><br>",
    "<span style='color: #2e2e2e;'>腫れ</span>が引かない <span style='color: #bfbfbf;'>Hare ga hikanai - The swelling isn't going down</span><br>",
    "<span style='color: #2e2e2e;'>腫瘍</span>が原因で痛みが出ています <span style='color: #bfbfbf;'>Shuyou ga gen'in de itami ga dete imasu - Pain is occurring due to the tumor</span><br>",
    "<span style='color: #2e2e2e;'>腫れ止め</span>の薬を塗った <span style='color: #bfbfbf;'>Hare dome no kusuri o nutta - I applied some anti-swelling medicine</span><br>",];
export const tenExample4 = [
    "彼は<span style='color: #2e2e2e;'>疾患</span>を抱えています <span style='color: #bfbfbf;'>Kare wa shikkan o kakaete imasu - He has a medical condition</span><br>",
    "<span style='color: #2e2e2e;'>疾患</span>の症状が出てきた <span style='color: #bfbfbf;'>Shikkan no shoujou ga dete kita - The symptoms of the illness appeared</span><br>",
    "<span style='color: #2e2e2e;'>疾病</span>を治療する必要があります <span style='color: #bfbfbf;'>Shippei o chiryou suru hitsuyou ga arimasu - There is a need to treat the disease</span><br>",
    "<span style='color: #2e2e2e;'>疾患</span>の治療法を探しています <span style='color: #bfbfbf;'>Shikkan no chiryouhou o sagashite imasu - Looking for treatment options for the illness</span><br>",
    "その<span style='color: #2e2e2e;'>疾患</span>は遺伝的な要素がある <span style='color: #bfbfbf;'>Sono shikkan wa iden-teki na youso ga aru - That illness has a genetic component</span><br>",
    "<span style='color: #2e2e2e;'>疾患</span>の早期発見が重要です <span style='color: #bfbfbf;'>Shikkan no souki hakken ga juuyou desu - Early detection of the illness is important</span><br>",
    "<span style='color: #2e2e2e;'>疾患</span>のリスクを減らす方法を知りたい <span style='color: #bfbfbf;'>Shikkan no risuku o herasu houhou o shiritai - I want to know ways to reduce the risk of illness</span><br>",
    "彼は病気で<span style='color: #2e2e2e;'>疾走</span>している <span style='color: #bfbfbf;'>Kare wa byouki de shissou shite iru - He's running a fever due to sickness</span><br>",
    "その<span style='color: #2e2e2e;'>疾患</span>はかなり重篤です <span style='color: #bfbfbf;'>Sono shikkan wa kanari jutoku desu - That illness is quite severe</span><br>",
    "<span style='color: #2e2e2e;'>疾病</span>にかかるのを予防するために手を洗いましょう <span style='color: #bfbfbf;'>Shippei ni kakaru no o yobou suru tame ni te o araimashou - Let's wash our hands to prevent illness</span>"];
export const tenExample5 = [
    "<span style='color: #2e2e2e;'>匿名</span> で投稿することができます <span style='color: #bfbfbf;'>Tokumei de toukou suru koto ga dekimasu - You can post anonymously</span><br>",
    "<span style='color: #2e2e2e;'>匿名性</span> を保つために、偽名を使うことがあります <span style='color: #bfbfbf;'>Tokumei-sei o tamotsu tame ni, gimei o tsukau koto ga arimasu - To maintain anonymity, one may use a false name</span><br>",
    "<span style='color: #2e2e2e;'>匿名性</span>を重んじる人もいます <span style='color: #bfbfbf;'>Tokumeisei o omonjiru hito mo imasu. - There are people who value anonymity</span><br>",
    "彼は<span style='color: #2e2e2e;'>匿名</span>でそのフォーラムに投稿した <span style='color: #bfbfbf;'>Kare wa tokumei de sono fo-ramu ni toukou shita - He posted on that forum anonymously</span><br>",
    "私は<span style='color: #2e2e2e;'>匿名</span>の手紙を受け取ったことがあります <span style='color: #bfbfbf;'>Watashi wa tokumei no tegami o uketotta koto ga arimasu - I have received an anonymous letter before</span><br>",
    "<span style='color: #2e2e2e;'>匿名性</span>を保つことはオンラインのセキュリティに関して重要です <span style='color: #bfbfbf;'>Tokumeisei o tamotsu koto wa onrain no sekuriti ni kan shite juuyou desu - Maintaining anonymity is important for online security</span><br>",
    "そのウェブサイトでは、<span style='color: #2e2e2e;'>匿名</span>で質問をすることができます <span style='color: #bfbfbf;'>Sono webusaito de wa, tokumei de shitsumon o suru koto ga dekimasu - On that website, you can ask questions anonymously</span><br>",
    "<span style='color: #2e2e2e;'>匿名性</span>を守るために、プライバシー設定を確認しましょう <span style='color: #bfbfbf;'>Tokumeisei o mamoru tame ni, puraibashii settei o kakunin shimashou - To protect anonymity, let's check the privacy settings</span><br>",
    "彼は<span style='color: #2e2e2e;'>匿名</span>で寄付をした <span style='color: #bfbfbf;'>Kare wa tokumei de kifu o shita - He made a donation anonymously</span><br>",
    "<span style='color: #2e2e2e;'>匿名</span>の通報者が事件の解決に役立った <span style='color: #bfbfbf;'>Tokumei no tsuuhousha ga jiken no kaiketsu ni yakudatta - An anonymous tipster helped solve the case</span><br>",];
export const tenExample6 = [
    "私の制服は<span style='color: #2e2e2e;'>紺色</span>です <span style='color: #bfbfbf;'>Watashi no seifuku wa koniro desu - My uniform is navy blue</span><br>",
    "<span style='color: #2e2e2e;'>紺色</span>の靴を買いたいです <span style='color: #bfbfbf;'>Koniro no kutsu o kaitai desu - I want to buy navy blue shoes</span><br>",
    "彼は<span style='color: #2e2e2e;'>紺色</span>のネクタイを着ています <span style='color: #bfbfbf;'>Kare wa koniro no nekutai o kiteimasu - He is wearing a navy blue tie</span><br>",
    "<span style='color: #2e2e2e;'>紺色</span>は私の好きな色です <span style='color: #bfbfbf;'>Koniro wa watashi no suki na iro desu - Navy blue is my favorite color</span><br>",
    "<span style='color: #2e2e2e;'>紺色</span>のジャケットを見つけました <span style='color: #bfbfbf;'>Koniro no jaketto o mitsukemashita - I found a navy blue jacket</span><br>",
    "この<span style='color: #2e2e2e;'>紺色</span>のカバンは素敵ですね <span style='color: #bfbfbf;'>Kono koniro no kaban wa suteki desu ne - This navy blue bag is lovely, isn't it?</span><br>",
    "彼女は<span style='color: #2e2e2e;'>紺色</span>のスカートを着ています <span style='color: #bfbfbf;'>Kanojo wa koniro no sukāto o kiteimasu - She is wearing a navy blue skirt</span><br>",
    "<span style='color: #2e2e2e;'>紺色</span>の空はとても美しいです <span style='color: #bfbfbf;'>Koniro no sora wa totemo utsukushii desu - The navy blue sky is very beautiful</span><br>",
    "<span style='color: #2e2e2e;'>紺色</span>の花瓶を机の上に置いてください <span style='color: #bfbfbf;'>Koniro no kabin o tsukue no ue ni oite kudasai - Please put the navy blue vase on the desk</span><br>",
    "<span style='color: #2e2e2e;'>紺色</span>のストールを買いました <span style='color: #bfbfbf;'>Koniro no sutōru o kaimashita - I bought a navy blue scarf</span><br>",
];
export const tenExample7 = [
    "<span style='color: #2e2e2e;'>帽子</span>をかぶって外出しましょう <span style='color: #bfbfbf;'>Bōshi o kabutte gaishutsu shimashou - Let's wear hats and go outside</span><br>",
    "彼はいつも<span style='color: #2e2e2e;'>帽子</span>をかぶっています <span style='color: #bfbfbf;'>Kare wa itsumo bōshi o kabutteimasu - He always wears a hat</span><br>",
    "その<span style='color: #2e2e2e;'>帽子</span>はとてもかわいいですね <span style='color: #bfbfbf;'>Sono bōshi wa totemo kawaii desu ne - That hat is very cute</span><br>",
    "<span style='color: #2e2e2e;'>帽子</span>を買うために店に行きます <span style='color: #bfbfbf;'>Bōshi o kau tame ni mise ni ikimasu - I'm going to the store to buy a hat</span><br>",
    "<span style='color: #2e2e2e;'>帽子</span>を取ると、髪がぱさぱさになります <span style='color: #bfbfbf;'>Bōshi o toru to, kami ga pasapasa ni narimasu - When I take off my hat, my hair gets messy</span><br>",
    "この<span style='color: #2e2e2e;'>帽子</span>は夏にぴったりです <span style='color: #bfbfbf;'>Kono bōshi wa natsu ni pittari desu - This hat is perfect for summer</span><br>",
    "<span style='color: #2e2e2e;'>帽子</span>を洗濯する方法を教えてください <span style='color: #bfbfbf;'>Bōshi o sentaku suru hōhō o oshiete kudasai - Please teach me how to wash a hat</span><br>",
    "彼女は<span style='color: #2e2e2e;'>帽子</span>が似合いますね <span style='color: #bfbfbf;'>Kanojo wa bōshi ga niaimasu ne - Hats suit her well</span><br>",
    "この<span style='color: #2e2e2e;'>帽子</span>は日差しを遮るのに良さそうです <span style='color: #bfbfbf;'>Kono bōshi wa hizashi o saegiru noni yosasou desu - This hat looks good for blocking the sunlight</span><br>",
    "<span style='color: #2e2e2e;'>帽子</span>を被ると、寒さから守られます <span style='color: #bfbfbf;'>Bōshi o kaburu to, samusa kara mamoraremasu - Wearing a hat protects you from the cold</span><br>",
];
export const tenExample8 = [
    "<span style='color: #2e2e2e;'>鼓</span>を演奏するのが好きです <span style='color: #bfbfbf;'>Tsuzumi o ensō suru no ga suki desu - I like playing the drum</span><br>",
    "彼は<span style='color: #2e2e2e;'>鼓</span>の音に合わせて踊ります <span style='color: #bfbfbf;'>Kare wa tsuzumi no oto ni awasete odorimasu - He dances to the beat of the drum</span><br>",
    "<span style='color: #2e2e2e;'>鼓</span>のリズムに合わせて歩く <span style='color: #bfbfbf;'>Tsuzumi no rizumu ni awasete aruku - Walk to the rhythm of the drums</span><br>",
    "<span style='color: #2e2e2e;'>鼓</span>を叩くとストレスが解消されます <span style='color: #bfbfbf;'>Tsuzumi o tataku to sutoresu ga kaishō saremasu - Playing the drum helps relieve stress</span><br>",
    "仲間の支持は彼を<span style='color: #2e2e2e;'>鼓舞</span>している <span style='color: #bfbfbf;'>Nakama no shiji wa kare o kobu shiteiru - The support of his friends is encouraging him</span><br>",
    "不安で<span style='color: #2e2e2e;'>鼓動</span>が速くなることがある <span style='color: #bfbfbf;'>Fuan de kodō ga hayaku naru koto ga aru - Sometimes anxiety makes the heartbeat faster</span><br>",
    "突然の大きな音で<span style='color: #2e2e2e;'>鼓膜</span>が痛んだ <span style='color: #bfbfbf;'>Totsuzen no ōkina oto de komaku ga itanda - My eardrums hurt from the sudden loud noise</span><br>",
    "先生は生徒たちを励まし<span style='color: #2e2e2e;'>鼓した</span> <span style='color: #bfbfbf;'>Sensei wa seito-tachi o hagemashi odoshita - The teacher encouraged and motivated the students</span><br>",
    "彼女の言葉は私に勇気を<span style='color: #2e2e2e;'>鼓舞した</span> <span style='color: #bfbfbf;'>Kanojo no kotoba wa watashi ni yūki o kobu shita - Her words encouraged me and gave me courage</span><br>",
    "<span style='color: #2e2e2e;'>鼓</span>を手に取り、こころゆくまで演奏しました <span style='color: #bfbfbf;'>Tsuzumi o te ni tori, kokoro yuku made ensō shimashita - I took the drum in my hands and played to my heart's content</span><br>",
];
export const tenExample9 = [
    "口の中を<span style='color: #2e2e2e;'>潤す</span>ために水を飲んだ <span style='color: #bfbfbf;'>Kuchi no naka o uruosu tame ni mizu o nonda - I drank water to moisten my mouth</span><br>",
    "花が雨で<span style='color: #2e2e2e;'>潤った</span> <span style='color: #bfbfbf;'>Hana ga ame de uruotta - The flowers were moistened by the rain</span><br>",
    "<span style='color: #2e2e2e;'>潤い</span>のある空気が気持ちいい <span style='color: #bfbfbf;'>Uruoi no aru kūki ga kimochi ī - The air with moisture feels pleasant</span><br>",
    "ボディローションを使って肌を<span style='color: #2e2e2e;'>潤わせる</span> <span style='color: #bfbfbf;'>Bodi rōshon o tsukatte hada o uruwaseru - Use body lotion to moisturize your skin</span><br>",
    "雨が地面を<span style='color: #2e2e2e;'>潤してくれた</span> <span style='color: #bfbfbf;'>Ame ga jimen o uruoshite kureta - The rain moistened the ground for us</span><br>",
    "自転車のチェーンに<span style='color: #2e2e2e;'>潤滑剤</span>を塗りました <span style='color: #bfbfbf;'>Jitensha no chēn ni junkatsuzai o nurimashita - I applied lubricant to the bicycle chain</span><br>",
    "この地域は水が<span style='color: #2e2e2e;'>潤沢</span>です <span style='color: #bfbfbf;'>Kono chiiki wa mizu ga junsaku desu - This area has an abundant water supply</span><br>",
    "その地域は自然資源が<span style='color: #2e2e2e;'>潤沢</span>で有名です <span style='color: #bfbfbf;'>Sono chiiki wa shizen shigen ga junsaku de yuumei desu - That region is famous for its abundant natural resources</span><br>",
    "工場の機械には定期的に<span style='color: #2e2e2e;'>潤滑油</span>を補充する必要があります <span style='color: #bfbfbf;'>Koujou no kikai ni wa teikiteki ni junkatsuyu o hokan suru hitsuyou ga arimasu - The machines in the factory need regular replenishment of lubricating oil</span><br>",
    "農場では、作物に必要な水が<span style='color: #2e2e2e;'>潤沢</span>に供給されます <span style='color: #bfbfbf;'>Noujou de wa, sakumotsu ni hitsuyou na mizu ga junsaku ni kyoukyuu saremasu - The farm has abundant water supply for the crops</span><br>",
    
];
export const tenExample10 = [
    "この夜は豪華な<span style='color: #2e2e2e;'>宴</span>が開かれる予定です <span style='color: #bfbfbf;'>Kono yoru wa gouka na utage ga hirakareru yotei desu - A lavish feast is scheduled for tonight</span><br>",
    "<span style='color: #2e2e2e;'>宴</span>の席で楽しい時間を過ごしました <span style='color: #bfbfbf;'>Utage no seki de tanoshii jikan o sugoshimashita - I had a great time at the banquet</span><br>",
    "彼の誕生日は<span style='color: #2e2e2e;'>宴</span>を開くのに最適な日です <span style='color: #bfbfbf;'>Kare no tanjoubi wa utage o hiraku noni saiteki na hi desu - His birthday is the perfect day for a feast</span><br>",
    "会社の年末の<span style='color: #2e2e2e;'>宴</span>はとても楽しいです <span style='color: #bfbfbf;'>Kaisha no nenmatsu no en wa totemo tanoshii desu - The company's year-end banquet is very enjoyable</span><br>",
    "彼らは毎年、家族で<span style='color: #2e2e2e;'>宴</span>を開いています <span style='color: #bfbfbf;'>Karera wa maitoshi, kazoku de en o hiraiteimasu - They hold a family banquet every year</span><br>",
    "友達との<span style='color: #2e2e2e;'>宴</span>はいつも盛り上がります <span style='color: #bfbfbf;'>Tomodachi to no en wa itsumo moriagari masu - Banquets with friends are always lively</span><br>",
    "豪華な<span style='color: #2e2e2e;'>宴</span>で美味しい料理を楽しみました <span style='color: #bfbfbf;'>Gouka na en de oishii ryouri o tanoshimimashita - I enjoyed delicious dishes at a lavish banquet</span><br>",
    "今夜は家族と一緒に賑やかな<span style='color: #2e2e2e;'>宴</span>を楽しみます <span style='color: #bfbfbf;'>Konya wa kazoku to issho ni nigiyaka na en o tanoshimimasu - Tonight, I'll enjoy a lively banquet with my family</span><br>",
    "先週の結婚式の<span style='color: #2e2e2e;'>宴</span>は素晴らしかったですね <span style='color: #bfbfbf;'>Senshuu no kekkonshiki no en wa subarashikatta desu ne - The banquet at last week's wedding was wonderful, wasn't it</span><br>",
    "彼の功績を祝うために<span style='color: #2e2e2e;'>宴</span>を計画しています <span style='color: #bfbfbf;'>Kare no kouseki o iwau tame ni en o keikaku shiteimasu - We are planning a banquet to celebrate his achievements</span><br>",
];
export const tenExample11 = [
    "彼は国に<span style='color: #2e2e2e;'>貢献する</span>ために尽力しています <span style='color: #bfbfbf;'>Kare wa kuni ni kouken suru tame ni jinryoku shiteimasu - He is making efforts to contribute to the country</span><br>",
    "古代の王たちは<span style='color: #2e2e2e;'>貢物</span>を差し出すことが求められました <span style='color: #bfbfbf;'>Kodai no ō-tachi wa koumotsu o sashidasu koto ga motomeraremashita - Ancient kings were required to present tributes</span><br>",
    "彼女は毎月、慈善団体に<span style='color: #2e2e2e;'>貢献しています</span> <span style='color: #bfbfbf;'>Kanojo wa maitsuki, jizen dantai ni kouken shiteimasu - She contributes to a charity organization every month</span><br>",
    "社会への<span style='color: #2e2e2e;'>貢献</span>は多岐にわたることが重要です <span style='color: #bfbfbf;'>Shakai e no kouken wa takawa ni wataru koto ga juuyou desu - Contributions to society come in various forms and are essential</span><br>",
    "<span style='color: #2e2e2e;'>貢物</span>は古代の文化交流で重要な役割を果たしました <span style='color: #bfbfbf;'>Koumotsu wa kodai no bunka kouryuu de juuyou na yakuwari o hatashimashita - Tributes played a significant role in ancient cultural exchanges</span><br>",
    "彼の<span style='color: #2e2e2e;'>貢献</span>がプロジェクトの成功につながりました <span style='color: #bfbfbf;'>Kare no kouken ga purojekuto no seikou ni tsunagarimashita - His contribution led to the success of the project</span><br>",
    "社会に<span style='color: #2e2e2e;'>貢献する</span>ことは大切なことです <span style='color: #bfbfbf;'>Shakai ni kouken suru koto wa taisetsu na koto desu - Contributing to society is important</span><br>",
    "彼女は環境保護に<span style='color: #2e2e2e;'>貢献しています</span> <span style='color: #bfbfbf;'>Kanojo wa kankyou hogo ni kouken shiteimasu - She is contributing to environmental conservation</span><br>",
    "古代の王国では、<span style='color: #2e2e2e;'>貢納</span>が課せられていました <span style='color: #bfbfbf;'>Kodai no oukoku de wa, kounou ga kasesareteimashita - Ancient kingdoms imposed tribute payments</span><br>",
    "<span style='color: #2e2e2e;'>貢納</span>が国の財政に影響を与えました <span style='color: #bfbfbf;'>Kounou ga kuni no zaisei ni eikyou o ataemashita - Tribute payments affected the country's finances</span><br>",
];
export const tenExample12 = [
    "最近、彼は<span style='color: #2e2e2e;'>痩せてきたね</span> <span style='color: #bfbfbf;'>Saikin, kare wa yasete kita ne - Lately, he has become thinner</span><br>",
    "健康的に<span style='color: #2e2e2e;'>痩せる</span>ために運動を始めました <span style='color: #bfbfbf;'>Kenkouteki ni yaseru tame ni undou o hajimemashita - I started exercising to become thin in a healthy way</span><br>",
    "ストレスが原因で<span style='color: #2e2e2e;'>痩せてしまった</span> <span style='color: #bfbfbf;'>Sutoresu ga gen'in de yasete shimatta - I became thin due to stress</span><br>",
    "彼女はダイエットで<span style='color: #2e2e2e;'>痩せた</span>そうです <span style='color: #bfbfbf;'>Kanojo wa daietto de yaseta sou desu - She seems to have become thin through dieting</span><br>",
    "彼は病気で急に<span style='color: #2e2e2e;'>痩せてしまった</span> <span style='color: #bfbfbf;'>Kare wa byouki de kyuu ni yasete shimatta - He became thin suddenly due to illness</span><br>",
    "彼女は<span style='color: #2e2e2e;'>痩身</span>な体型を保つために運動しています <span style='color: #bfbfbf;'>Kanojo wa soushin na taigata o tamotsu tame ni undou shiteimasu - She exercises to maintain a slim figure</span><br>",
    "あのモデルは<span style='color: #2e2e2e;'>痩身</span>で知られています <span style='color: #bfbfbf;'>Ano moderu wa soushin de shirareteimasu - That model is known for her slim figure</span><br>",
    "<span style='color: #2e2e2e;'>痩せ肉</span>は低脂肪でヘルシーな選択です <span style='color: #bfbfbf;'>Yase niku wa teishibou de herushii na sentaku desu - Lean meat is a healthy and low-fat choice</span><br>",
    "<span style='color: #2e2e2e;'>痩身</span>を目指して、毎日ジョギングをしています <span style='color: #bfbfbf;'>Soushin o mezashite, mainichi jogingu o shiteimasu - Aiming for a slim figure, I jog every day</span><br>",
    "彼女は<span style='color: #2e2e2e;'>痩身</span>な体型を保つために運動しています <span style='color: #bfbfbf;'>Kanojo wa soushin na taigata o tamotsu tame ni undou shiteimasu - She exercises to maintain a slim figure</span><br>",
];
export const tenExample13 = [
    "彼は私に大きな<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>を受けました <span style='color: #bfbfbf;'>Kare wa watashi ni ooki na on o ukemashita - He received a great favor from me</span><br>",
    "<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>を仇で返すことはできません <span style='color: #bfbfbf;'>On o adade kaesu koto wa dekimasen - You can't repay kindness with ingratitude</span><br>",
    "彼は<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>を忘れることはありません <span style='color: #bfbfbf;'>Kare wa on o wasureru koto wa arimasen - He never forgets a favor</span><br>",
    "<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>には<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>で返すのが礼儀です <span style='color: #bfbfbf;'>On ni wa on de kaesu no ga reigi desu - It's proper etiquette to repay a favor with a favor</span><br>",
    "その人はいつも<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>を忘れずに生きています <span style='color: #bfbfbf;'>Sono hito wa itsumo on o wasurezu ni ikiteimasu - That person always lives without forgetting favors</span><br>",
    "彼女は私に<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>を感じさせることができる人です <span style='color: #bfbfbf;'>Kanojo wa watashi ni on o kanjisaseru koto ga dekiru hito desu - She's someone who can make me feel grateful</span><br>",
    "<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>は忘れたりしません <span style='color: #bfbfbf;'>On wa wasuretari shimasen - Favors should not be forgotten</span><br>",
    "その人は多くの人々に<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>を着せています <span style='color: #bfbfbf;'>Sono hito wa ooku no hitobito ni on o kiseteimasu - That person has shown kindness to many people</span><br>",
    "<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>を仇で返さないように心がけています <span style='color: #bfbfbf;'>On o adade kae sanai you ni kokorogaketeimasu - I try not to repay kindness with ingratitude</span><br>",
    "<span style='color: #2e2e2e;'>痩せてきたね</span>恩</span>は大切にしなければいけません <span style='color: #bfbfbf;'>On wa taisetsu ni shinakereba ikemasen - We must treasure favors</span><br>",
];
export const tenExample14 = [
    "彼は秘密裏に計画を<span style='color: #2e2e2e;'>謀っていた</span> <span style='color: #bfbfbf;'>Kare wa himitsurani keikaku o hakatteita - He was secretly plotting a plan</span><br>",
    "敵は次なる一手を<span style='color: #2e2e2e;'>謀っている</span>かもしれません <span style='color: #bfbfbf;'>Teki wa tsuginaru itte o hakatteiru kamoshiremasen - The enemy may be plotting their next move</span><br>",
    "陰湿な<span style='color: #2e2e2e;'>陰謀を謀る者がいる</span>かもしれない <span style='color: #bfbfbf;'>Inshitsu na inbou o hakaru mono ga iru kamoshirenai - There might be someone plotting a malicious conspiracy</span><br>",
    "彼は政敵を<span style='color: #2e2e2e;'>謀る</span>ために情報を集めている <span style='color: #bfbfbf;'>Kare wa seihoku o hakaru tame ni jouhou o atsumeteiru - He is gathering information to plot against his political rival</span><br>",
    "その犯罪者は狡猾な<span style='color: #2e2e2e;'>謀</span>を巡らしている <span style='color: #bfbfbf;'>Sono hanzai-sha wa koukatsu na bou o megurashiteiru - The criminal is weaving cunning schemes</span><br>",
    "彼は邪悪な<span style='color: #2e2e2e;'>謀</span>を企んでいるようだ <span style='color: #bfbfbf;'>Kare wa jaaku na bou o takurandeiru you da - It seems like he's planning something wicked</span><br>",
    "政治の世界は裏で様々な<span style='color: #2e2e2e;'>謀</span>が渦巻いている <span style='color: #bfbfbf;'>Seiji no sekai wa ura de samazama na bou ga uzumaiteiru - The world of politics is swirling with various plots behind the scenes</span><br>",
    "そのグループは大胆な<span style='color: #2e2e2e;'>謀</span>を実行した <span style='color: #bfbfbf;'>Sono guruupu wa daitan na bou o jikkou shita - The group executed a bold plot</span><br>",
    "事件には悪賢い<span style='color: #2e2e2e;'>謀</span>があるようです <span style='color: #bfbfbf;'>Jiken niwa warukashikoi bou ga aru you desu - It seems there's a cunning plot behind the incident</span><br>",
    "彼は自分の利益のために<span style='color: #2e2e2e;'>謀</span>をめぐらしている <span style='color: #bfbfbf;'>Kare wa jibun no rieki no tame ni bou o megurashiteiru - He is scheming for his own benefit</span><br>",
];
export const tenExample15 = [
    "その風車は風の力で<span style='color: #2e2e2e;'>旋回しています</span> <span style='color: #bfbfbf;'>Sono fuusha wa kaze no chikara de senkai shiteimasu - That windmill is rotating with the power of the wind</span><br>",
    "ダンサーの<span style='color: #2e2e2e;'>旋律</span>は美しい踊りを彩ります <span style='color: #bfbfbf;'>Dansaa no senritsu wa utsukushii odori o irodorimasu - The dancer's rhythm enhances the beauty of the dance</span><br>",
    "<span style='color: #2e2e2e;'>旋回する</span>飛行機の音が聞こえました <span style='color: #bfbfbf;'>Senkai suru hikouki no oto ga kikoemashita - I heard the sound of a rotating airplane</span><br>",
    "時計の針が<span style='color: #2e2e2e;'>旋回し続けています</span> <span style='color: #bfbfbf;'>Tokei no hari ga senkai shi tsuzuketeimasu - The clock hands continue to rotate</span><br>",
    "その映画は一つの物語を<span style='color: #2e2e2e;'>旋律しています</span> <span style='color: #bfbfbf;'>Sono eiga wa hitotsu no monogatari o kaiten shiteimasu - That movie revolves around one story</span><br>",
    "色彩の<span style='color: #2e2e2e;'>旋律</span>が絵画の美しさを際立たせます <span style='color: #bfbfbf;'>Shikisai no senritsu ga kaiga no utsukushisa o kiwadatase masu - The color scheme accentuates the beauty of the painting</span><br>",
    "地球の自転は一日に一度<span style='color: #2e2e2e;'>旋回します</span> <span style='color: #bfbfbf;'>Chikyuu no jituen wa ichinichi ni ichido senkai shimasu - The Earth rotates once a day</span><br>",
    "彼の話は主題を<span style='color: #2e2e2e;'>旋回しました</span> <span style='color: #bfbfbf;'>Kare no hanashi wa shudai o senkai shimashita - His story revolved around the main theme</span><br>",
    "<span style='color: #2e2e2e;'>旋回する</span>カルーセルは子供たちの楽しみです <span style='color: #bfbfbf;'>Senkai suru karuusel wa kodomotachi no tanoshimi desu - The rotating carousel is a delight for children</span><br>",
    "風船は空でゆっくりと<span style='color: #2e2e2e;'>旋回していました</span> <span style='color: #bfbfbf;'>Fuusen wa sora de yukkuri to senkai shiteimashita - The balloon was slowly rotating in the sky</span><br>",
];
export const tenExample16 = [
    "<span style='color: #2e2e2e;'>盾</span>を持って、彼は戦いに備えた <span style='color: #bfbfbf;'>Tate o motte, kare wa tatakai ni sonaeta - He prepared for battle with a shield in hand</span><br>",
    "古代の戦士たちは<span style='color: #2e2e2e;'>盾</span>を使って身を守った <span style='color: #bfbfbf;'>Kodai no senshi-tachi wa tate o tsukatte mi o mamotta - Ancient warriors protected themselves using shields</span><br>",
    "<span style='color: #2e2e2e;'>盾</span>は攻撃から身を守るための大切な道具です <span style='color: #bfbfbf;'>Tate wa kougeki kara mi o mamoru tame no taisetsu na dougu desu - A shield is an important tool for protecting oneself from attacks</span><br>",
    "彼は信念を<span style='color: #2e2e2e;'>盾</span>にして立ち向かった <span style='color: #bfbfbf;'>Kare wa shinnen o tate ni shite tachimukatta - He faced it with his beliefs as his shield</span><br>",
    "<span style='color: #2e2e2e;'>盾</span>を持つことは自己防衛の手段です <span style='color: #bfbfbf;'>Tate o motsu koto wa jiko bouei no shudan desu - Holding a shield is a means of self-defense</span><br>",
    "戦士たちは<span style='color: #2e2e2e;'>盾</span>を前に立てて進んだ <span style='color: #bfbfbf;'>Senshi-tachi wa tate o mae ni tatete susunda - The warriors advanced, holding their shields in front of them</span><br>",
    "<span style='color: #2e2e2e;'>盾</span>は戦場での生存を助ける役割を果たします <span style='color: #bfbfbf;'>Tate wa senjou de no seizon o tasukeru yakuwari o hatashimasu - Shields play a role in aiding survival on the battlefield</span><br>",
    "その<span style='color: #2e2e2e;'>盾</span>は重厚な作りでした <span style='color: #bfbfbf;'>Sono tate wa juukou na tsukurideshita - That shield was made with a sturdy build</span><br>",
    "彼は<span style='color: #2e2e2e;'>盾</span>を携えて旅をすることに決めた <span style='color: #bfbfbf;'>Kare wa tate o tazusaete tabi o suru koto ni kimeta - He decided to travel carrying a shield</span><br>",
    "<span style='color: #2e2e2e;'>盾</span>を持つことは危険から身を守る手段です <span style='color: #bfbfbf;'>Tate o motsu koto wa kiken kara mi o mamoru shudan desu - Holding a shield is a means to protect oneself from danger</span><br>",
];
export const tenExample17 = [
    "<span style='color: #2e2e2e;'>寮生活</span>は新しい友達をたくさん作る機会です <span style='color: #bfbfbf;'>Ryou seikatsu wa atarashii tomodachi o takusan tsukuru kikai desu - Dorm life is an opportunity to make many new friends</span><br>",
    "大学の<span style='color: #2e2e2e;'>寮</span>には共有のキッチンがあります <span style='color: #bfbfbf;'>Daigaku no ryou ni wa kyoyuu no kitchin ga arimasu - The university dormitory has a shared kitchen</span><br>",
    "<span style='color: #2e2e2e;'>寮</span>での生活は自立心を育てるいい機会です <span style='color: #bfbfbf;'>Ryou de no seikatsu wa jiritsushin o sodateru ii kikai desu - Living in a dormitory is a good opportunity to foster independence</span><br>",
    "彼は学校の<span style='color: #2e2e2e;'>寮</span>に住んでいます <span style='color: #bfbfbf;'>Kare wa gakkou no ryou ni sundeimasu - He lives in the school dormitory</span><br>",
    "<span style='color: #2e2e2e;'>寮</span>には共有のバスルームもあります <span style='color: #bfbfbf;'>Ryou ni wa kyoyuu no basuruumu mo arimasu - There is also a shared bathroom in the dormitory</span><br>",
    "大学に入るときに、<span style='color: #2e2e2e;'>寮</span>に住むことを選びました <span style='color: #bfbfbf;'>Daigaku ni hairu toki ni, ryou ni sumu koto o erabimashita - When entering college, I chose to live in the dormitory</span><br>",
    "<span style='color: #2e2e2e;'>寮</span>での生活は貴重な経験になることが多いです <span style='color: #bfbfbf;'>Ryou de no seikatsu wa kichou na keiken ni naru koto ga ooi desu - Life in the dormitory often becomes a valuable experience</span><br>",
    "この<span style='color: #2e2e2e;'>寮</span>は施設が整っていて快適です <span style='color: #bfbfbf;'>Kono ryou wa shisetsu ga tootteite kaiteki desu - This dormitory is well-equipped and comfortable</span><br>",
    "学校の<span style='color: #2e2e2e;'>寮</span>は学生の間で人気があります <span style='color: #bfbfbf;'>Gakkou no ryou wa gakusei no aida de ninki ga arimasu - The school dormitory is popular among students</span><br>",
    "<span style='color: #2e2e2e;'>寮生活</span>は新しい環境に適応する手助けになります <span style='color: #bfbfbf;'>Ryou seikatsu wa atarashii kankyou ni tekiou suru tedasuke ni narimasu - Dorm life helps adapt to new environments</span>",
];
export const tenExample18 = [
    "そのナイフの<span style='color: #2e2e2e;'>刃</span>が鋭いです <span style='color: #bfbfbf;'>Sono naifu no ha ga surudoi desu - The blade of that knife is sharp</span><br>",
    "<span style='color: #2e2e2e;'>刃物</span>を使うときは注意が必要です <span style='color: #bfbfbf;'>Hamono o tsukau toki wa chuui ga hitsuyou desu - Caution is necessary when using sharp objects</span><br>",
    "彼は<span style='color: #2e2e2e;'>刃物</span>の取り扱いに慣れています <span style='color: #bfbfbf;'>Kare wa hamono no toriatsukai ni nareteimasu - He is familiar with handling blades</span><br>",
    "斧の<span style='color: #2e2e2e;'>刃</span>を研いでください <span style='color: #bfbfbf;'>Ono no ha o toide kudasai - Please sharpen the blade of the axe</span><br>",
    "<span style='color: #2e2e2e;'>刃</span>のないナイフは使いにくいです <span style='color: #bfbfbf;'>Ha no nai naifu wa tsukai nikui desu - A knife without a blade is difficult to use</span><br>",
    "包丁の<span style='color: #2e2e2e;'>刃</span>が欠けてしまいました <span style='color: #bfbfbf;'>Houchou no ha ga kakete shimaimashita - The blade of the kitchen knife chipped</span><br>",
    "彼は<span style='color: #2e2e2e;'>刃物</span>を使う際に常に慎重です <span style='color: #bfbfbf;'>Kare wa hamono o tsukau sai ni tsune ni shinchou desu - He is always cautious when using blades</span><br>",
    "その<span style='color: #2e2e2e;'>刃</span>は切れ味がよくないです <span style='color: #bfbfbf;'>Sono ha wa kireaji ga yoku nai desu - That blade isn't very sharp</span><br>",
    "<span style='color: #2e2e2e;'>刃</span>を持つことは責任が伴います <span style='color: #bfbfbf;'>Ha o motsu koto wa sekinin ga tomonaimasu - Having a blade comes with responsibility</span><br>",
    "バリカンの<span style='color: #2e2e2e;'>刃</span>を交換する必要があります <span style='color: #bfbfbf;'>Barikan no ha o koukan suru hitsuyou ga arimasu - It's necessary to replace the blade of the hair clipper</span>",
];
export const tenExample19 = [
    "その新聞社は文化の<span style='color: #2e2e2e;'>啓蒙活動</span>を行っています <span style='color: #bfbfbf;'>Sono shinbunsha wa bunka no keimou katsudou o okonatteimasu - That newspaper company is engaged in cultural enlightenment activities</span><br>",
    "<span style='color: #2e2e2e;'>啓蒙活動</span>は知識を広めるために重要です <span style='color: #bfbfbf;'>Keimou katsudou wa chishiki o hirogeru tame ni juuyou desu - Enlightenment activities are important for spreading knowledge</span><br>",
    "彼の教育政策は国民の<span style='color: #2e2e2e;'>啓発</span>を目指しています <span style='color: #bfbfbf;'>Kare no kyouiku seisaku wa kokumin no keihatsu o mezashiteimasu - His educational policy aims at enlightening the citizens</span><br>",
    "<span style='color: #2e2e2e;'>啓発活動</span>は社会問題を解決するのに役立ちます <span style='color: #bfbfbf;'>Keihatsu katsudou wa shakai mondai o kaiketsu suru noni yakudachimasu - Awareness campaigns help in solving social issues</span><br>",
    "<span style='color: #2e2e2e;'>啓蒙運動</span>は社会の進歩に寄与します <span style='color: #bfbfbf;'>Keimou undou wa shakai no shinpo ni kiyoshimasu - Enlightenment movements contribute to the progress of society</span><br>",
    "彼は新しい技術の<span style='color: #2e2e2e;'>啓蒙</span>に尽力しています <span style='color: #bfbfbf;'>Kare wa atarashii gijutsu no keimou ni jinryoku shiteimasu - He is making efforts to enlighten people about new technologies</span><br>",
    "<span style='color: #2e2e2e;'>啓蒙活動</span>は多くの人々に影響を与えました <span style='color: #bfbfbf;'>Keimou katsudou wa ooku no hitobito ni eikyou o ataemashita - Enlightenment activities have influenced many people</span><br>",
    "その組織は<span style='color: #2e2e2e;'>啓蒙的</span>なイベントを開催しています <span style='color: #bfbfbf;'>Sono soshiki wa keimouteki na ibento o kaisai shiteimasu - That organization is hosting an enlightening event</span><br>",
    "<span style='color: #2e2e2e;'>啓蒙活動</span>は社会的変革を促進する役割を果たします <span style='color: #bfbfbf;'>Keimou katsudou wa shakaiteki henkaku o sokushin suru yakuwari o hatashimasu - Enlightenment activities play a role in promoting social change</span><br>",
    "<span style='color: #2e2e2e;'>啓蒙運動</span>は人々の意識を変えることができます <span style='color: #bfbfbf;'>Keimou undou wa hitobito no ishiki o kaeru koto ga dekimasu - Enlightenment movements can change people's consciousness</span>",
];
export const tenExample20 = [
    "彼の勇敢な行動は多くの<span style='color: #2e2e2e;'>誉れ</span>を受けました <span style='color: #bfbfbf;'>Kare no yuukan na koudou wa ooku no homare o ukemashita - His brave actions received much honor</span><br>",
    "<span style='color: #2e2e2e;'>誉れ高い功績</span>により、その将軍は武士たちから敬意を受けた <span style='color: #bfbfbf;'>Homare-takai kouseki ni yori, sono shougun wa bushi-tachi kara keii o uketa - Due to his honorable achievements, the general gained respect from the warriors</span><br>",
    "彼の卓越した才能は多くの<span style='color: #2e2e2e;'>誉れ</span>をもたらした <span style='color: #bfbfbf;'>Kare no takuetsu shita sainou wa ooku no homare o motarashita - His outstanding talent brought much honor</span><br>",
    "その作品は国際的な賞を受賞し、大きな<span style='color: #2e2e2e;'>誉れ</span>を受けました <span style='color: #bfbfbf;'>Sono sakuhin wa kokusaiteki na shou o jushou shi, ookina homare o ukemashita - The work received international awards, earning great honor</span><br>",
    "彼の人間性に対する<span style='color: #2e2e2e;'>誉れ</span>は広く知られています <span style='color: #bfbfbf;'>Kare no ningensei ni taisuru homare wa hiroku shirareteimasu - The honor for his character is widely known</span><br>",
    "<span style='color: #2e2e2e;'>誉れ高い</span>行為に感動し、彼に感謝の意を表明した <span style='color: #bfbfbf;'>Homare-takai koui ni kandou shi, kare ni kansha no i o hyoumei shita - Touched by the honorable act, they expressed gratitude to him</span><br>",
    "その文学賞は彼女に大いなる<span style='color: #2e2e2e;'>誉れ</span>をもたらしました <span style='color: #bfbfbf;'>Sono bungaku shou wa kanojo ni ooinaru homare o motarashimashita - The literary award brought great honor to her</span><br>",
    "地元の英雄は市民から<span style='color: #2e2e2e;'>誉れ高い</span>評価を受けています <span style='color: #bfbfbf;'>Jimoto no eiyuu wa shimin kara homare-takai hyouka o uketeimasu - The local hero is highly esteemed by the citizens</span><br>",
    "彼の成功に対して、上司は彼を<span style='color: #2e2e2e;'>褒めました</span> <span style='color: #bfbfbf;'>Kare no seikou ni taishite, joushi wa kare o homerimashita - The boss praised him for his success</span><br>",
    "子供が良い行動をしたら、必ず<span style='color: #2e2e2e;'>褒めてあげて</span>ください <span style='color: #bfbfbf;'>Kodomo ga ii koudou o shitara, kanarazu homeru teagete kudasai - Whenever a child behaves well, be sure to praise them</span>",
];


